site_name: Justice-Universe
nav:
  - Home: index.md
  - Keys: keys.md
  - Query: query.md
  - Transaction: tx.md
  - Supernode: supernode.md
  - Web Wallet: wallet.md
  - PC Wallet: wallet-electron.md
theme: readthedocs
