site_name: Justice-Universe
nav:
  - Home: index.md
  - Keys: keys.md
  - Query: query.md
  - Transaction: tx.md
  - Supernode: supernode.md
  - Wallet: wallet.md
  - Wallet PC app: wallet-electron.md
theme: readthedocs
